### ISSUE TITLE
How do I import footprint library in KiCAD?

### ISSUE THREAD

**Issue by ramandeep89** [judge2005/Eagle-Nixie-Libs#2]
Hi

KiCAD requires a .pretty folder for footprints and while I added the lib file, it only shows the symbol and not the PCB footprint. Any way I can resolve the issue?

**Comment by judge2005** [comment]
KiCAD doesn’t require a .pretty folder. It will load the .mod files for footprints.

**Comment by ramandeep89** [comment]
Ok. Got it to work. Didn't know I can add .mod legacy files directly. Thanks for the help and great project!

**Comment by Mek7** [comment]
Hello,
under latest KiCad 5.1.9-1 I can't add the mod files. I need kicad_mod files instead (in a .pretty folder). Mod files are legacy, according to what I could find.
As written here in this issue, it should somehow be possible to use the mod files as they are. But how? What does it mean to "add .mod files directly"?
Please mention that in the readme to avoid questions from other people. Thanks.

**Comment by Mek7** [comment]
So I finally managed to do it but it was very obscure and cumbersome. I am posting this in hope that it helps somebody else with the same problem.
Open your Footprint manager, switch to Project libraries tab, and enter the exact path to the .mod file. Do not use the file picker, because that only allows you to select whole folder, that won't work. The path must be to a file, not to a folder. And don't forget also to switch Plugin Type to Legacy.
Good luck.
![Capture](https://user-images.githubusercontent.com/12199478/105218002-e5759180-5b54-11eb-90f7-117bee3ef78f.JPG)

**Comment by twalter23** [comment]
Thanks, cumbersome it is indeed !
